name: Data Availability Visuals

on:
  push:
    branches:
      - '**' # FIXED: This universal pattern matches ALL branches, ensuring visibility on any new feature branch.
    paths:
      - '.github/workflows/data-availability-visuals.yml' # Only runs when this file is changed
  
  workflow_dispatch:
    inputs:
      csv_path:
        description: 'Path to the input CSV within the repo (e.g., xlsxConverted/csvFiles/dart-med-pop_decomp-dhi.csv)'
        required: true
        type: string
        default: 'xlsxConverted/csvFiles/dart-med-pop_decomp-dhi.csv'
      start_year:
        description: 'Clip to years >= start_year (optional)'
        required: false
        type: string
        default: ''
      end_year:
        description: 'Clip to years <= end_year (optional)'
        required: false
        type: string
        default: ''
      tick_interval:
        description: 'Tick mark spacing for x-axis (default: 5)'
        required: false
        type: string
        default: '5'
      glyph:
        description: 'Character to render for available data (default: #)'
        required: false
        type: string
        default: '#' 
      include_universal:
        description: 'Include Universal row (default: true)'
        required: false
        type: string
        default: 'true'
      visualization_mode: # Used by Python script to handle gridlines (vertical-grid-5yr, etc.)
        description: 'Defines the visual grid style for text/md output (e.g., minimal-ticks, vertical-grid-5yr, vertical-grid-1yr)'
        required: true
        type: string
        default: 'vertical-grid-5yr' 
      output_format: # Controls which file types are generated (text, png, pdf, etc.)
        description: 'Output format(s) to generate (comma-separated: text, md, png, pdf, svg, etc.)'
        required: true
        type: string
        default: 'text,md,png' 
        
jobs:
  generate-visuals:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Installing packages for image generation (PNG/PDF) and data handling
          pip install pandas numpy matplotlib seaborn

      - name: Generate visualizations
        run: |
          set -eux
          
          # --- DIAGNOSTIC STEP (KEEP FOR ROBUSTNESS) ---
          echo "--- Content of generate_visuals.py on runner ---"
          cat analysis/data-availability/visuals/generate_visuals.py
          echo "------------------------------------------------"
          
          # --- CRITICAL FIX: Determine CSV Path based on trigger ---
          CSV_PATH="${{ github.event.inputs.csv_path }}"
          if [ -z "$CSV_PATH" ]; then
            # Hardcode default path only if input is completely empty (i.e., push trigger)
            CSV_PATH="xlsxConverted/csvFiles/dart-med-pop_decomp-dhi.csv" 
          fi
          
          # Start CMD with the MANDATORY and now-guaranteed CSV Path
          CMD="python analysis/data-availability/visuals/generate_visuals.py --csv-path $CSV_PATH"
          
          # --- Conditionally add ALL optional arguments IF they have a value ---
          
          # Start Year
          if [ -n "${{ github.event.inputs.start_year }}" ]; then
            CMD="$CMD --start-year ${{ github.event.inputs.start_year }}"
          fi
          # End Year
          if [ -n "${{ github.event.inputs.end_year }}" ]; then
            CMD="$CMD --end-year ${{ github.event.inputs.end_year }}"
          fi
          # Tick Interval
          if [ -n "${{ github.event.inputs.tick_interval }}" ]; then
            CMD="$CMD --tick-interval ${{ github.event.inputs.tick_interval }}"
          fi
          # Glyph
          if [ -n "${{ github.event.inputs.glyph }}" ]; then
            CMD="$CMD --glyph \"${{ github.event.inputs.glyph }}\""
          fi
          # Include Universal
          if [ -n "${{ github.event.inputs.include_universal }}" ]; then
            CMD="$CMD --include-universal ${{ github.event.inputs.include_universal }}"
          fi
          
          # Visualization Mode (NEW ARGUMENT)
          if [ -n "${{ github.event.inputs.visualization_mode }}" ]; then
            CMD="$CMD --visualization-mode ${{ github.event.inputs.visualization_mode }}"
          fi
          
          # Output Format (NEW ARGUMENT)
          if [ -n "${{ github.event.inputs.output_format }}" ]; then
            CMD="$CMD --output-format ${{ github.event.inputs.output_format }}"
          fi
          
          # Execute the command
          eval $CMD

      - name: Commit and push visualization outputs (CRITICAL FIX)
        run: |
          set -eux
          
          # Set GitHub's standard bot credentials
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # General Fix: Add ALL generated files from the visuals directory.
          git add analysis/data-availability/visuals/* || true 
          
          if ! git diff --cached --quiet; then
            # 1. Commit the local changes (Git history is maintained locally)
            # Changed commit message for clarity of artifact update
            git commit -m "Update generated visualizations for ${{ github.event.inputs.csv_path }}"
            
            # 2. CRITICAL FIX: Push, forcing the update over any parallel remote push.
            # We skip pull/rebase and use --force-with-lease to safely overwrite artifacts.
            # ${{ github.ref_name }} correctly identifies the branch (e.g., EEbrami-generalizing)
            git push origin ${{ github.ref_name }} --force-with-lease
          else
            echo "No changes to commit."
          fi
